openapi: 3.0.0
info:
  version: '1.0'
  title: Benutzer
  description: 'Die HelpingHands-WebApp nutzt Microservices. In diesem werden die üblichen CRUD-Operationen zur Suche, Anzeige und Bearbeitung von Benutzer ermöglicht.'
  contact:
    name: 'Angelika Kleimann, Ayse Nur Kocak, Elena Väth, Marco Pelzer, Rebecca Piotrowski, Jonas Prions'
servers:
  - url: 'http://localhost:3001'
paths:
  /:
    get:
      tags:
        - Index
      summary: Wurzeladresse des Webservices
      description: HATEAOS-Links mit den Collections abrufen
      operationId: get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HATEOAS_Collection'
      servers:
        - url: 'http://localhost:3001'
  /benutzer:
    get:
      tags:
        - Benutzerliste
      summary: Benutzer sehen
      description: Benutzer einsehen
      operationId: get-benutzer
      parameters:
        - name: vorname
          in: query
          description: Gesuchter Vorname
          schema:
            type: string
        - name: nachname
          in: query
          description: Gesuchter Nachname
          schema:
            type: string
        - name: straße
          in: query
          description: Gesuchte Straße
          schema:
            type: string
        - name: hausnummer
          in: query
          description: Gesuchte Hausnummer
          schema:
            type: string
        - name: postleitzahl
          in: query
          description: Gesuchte Postleitzahl
          schema:
            type: string
        - name: stadt
          in: query
          description: Gesuchte Stadt
          schema:
            type: string
        - name: email
          in: query
          description: Gesuchte Email
          schema:
            type: string
        - name: telefon
          in: query
          description: Gesuchte Telefonnummer
          schema:
            type: string
        - name: nutzername
          in: query
          description: Gesuchter Nutzername
          schema:
            type: string
        - name: passwort
          in: query
          description: Gesuchtes Passwort
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Benutzer'
      servers:
        - url: 'http://localhost:3001'
    post:
      tags:
        - Benutzerliste
      summary: Benutzer anlegen
      description: 'Neuen Benutzer anlegen. Speichert den übergebenen Benutzer in der Datenbank. Der Wert des Feldes "_id" wird dabei ignoriert, da in jedem Fall eine neue Adresse mit neuer id angelegt wird.'
      operationId: post-benutzer
      requestBody:
        description: Daten des anzulegenden Benutzers
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Benutzer'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Benutzer'
          headers:
            Location:
              schema:
                type: string
              description: URL des angelegten Datensatzes
      servers:
        - url: 'http://localhost:3001'
  '/benutzer/{id}':
    get:
      tags:
        - Benutzer
      summary: Benutzer sehen
      description: Benutzer von Server lesen
      operationId: get-benutzer-id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Benutzer'
        '404':
          description: Not Found
      servers:
        - url: 'http://localhost:3001'
    put:
      tags:
        - Benutzer
      summary: Benutzer überschrieben
      description: 'Benutzer bearbeiten. Es könne alle Felder geändert werden, mit Ausnahme der id des Datensatzes. Der Versuch, die id zu ändern, wird vom Server stillschweigend ignoriert.'
      operationId: put-benutzer-id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Benutzer'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Benutzer'
        '404':
          description: Not Found
      servers:
        - url: 'http://localhost:3001'
    patch:
      tags:
        - Benutzer
      summary: Einzelne Felder ändern
      description: 'Benutzer bearbeiten. Es könne alle Felder geändert werden, mit Ausnahme der id des Datensatzes. Der Versuch, die id zu ändern, wird vom Server stillschweigend ignoriert.'
      operationId: patch-benutzer-id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Benutzer'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Benutzer'
        '404':
          description: Not Found
      servers:
        - url: 'http://localhost:3001'
    delete:
      tags:
        - Benutzer
      summary: Benutzer löschen
      description: Benutzer löschen
      operationId: delete-benutzer-id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
      servers:
        - url: 'http://localhost:3001'
tags:
  - name: Benutzer
  - name: Benutzerliste
  - name: Index
components:
  schemas:
    HATEOAS_Collection:
      type: object
      title: HATEOAS_Collection
      description: HATEOAS-Links einer Collection
      properties:
        _name:
          type: string
        query:
          $ref: '#/components/schemas/HATEOAS_Link'
        create:
          $ref: '#/components/schemas/HATEOAS_Link'
    HATEOAS_Link:
      type: object
      title: HATEOAS_Link
      description: HATEOAS-Link
      properties:
        url:
          type: string
        method:
          type: string
        query_params:
          type: array
          items:
            type: string
    Benutzer:
      type: object
      title: Benutzer
      description: Benutzer
      properties:
        _links:
          $ref: '#/components/schemas/HATEAOS_Resource'
        _id:
          type: string
        vorname:
          type: string
        nachname:
          type: string
        straße:
          type: string
        hausnummer:
          type: string
        postleitzahl:
          type: string
        stadt:
          type: string
        email:
          type: string
        telefon:
          type: string
        nutzername:
          type: string
        passwort:
          type: string
    HATEAOS_Resource:
      type: object
      title: HATEAOS_Resource
      description: HATEAOS-Links einer Ressource
      properties:
        read:
          $ref: '#/components/schemas/HATEOAS_Link'
        update:
          $ref: '#/components/schemas/HATEOAS_Link'
        patch:
          $ref: '#/components/schemas/HATEOAS_Link'
        delete:
          $ref: '#/components/schemas/HATEOAS_Link'
